modLoader="javafml"
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/Pdiddy973/AllTheCompressed/issues"
[[mods]]
modId="AllTheCompressed"
version="${file.jarVersion}"
displayName="AllTheCompressed"
displayURL="https://github.com/Pdiddy973/AllTheCompressed"
logoFile="examplemod.png"
credits="Thanks for this example mod goes to Java"
authors="Pdiddy973"
description='''
A Good Description
'''

[[dependencies.AllTheCompressed]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.AllTheCompressed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
