modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
issueTrackerURL="https://github.com/Pdiddy973/allthecompressed"

[[mods]]
modId="allthecompressed"
version="${file.jarVersion}"
displayName="allthecompressed"
displayURL="http://dinnerbeef.com"
logoFile=""
credits=" "
authors=" "
description='''  '''
