modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://github.com/Pdiddy973/AllTheCompressed/issues" #optional
[[mods]] #mandatory
modId="allthecompressed" #mandatory
version="${file.jarVersion}" #mandatory
displayName="AllTheCompressed" #mandatory
#displayURL="https://github.com/Pdiddy973/AllTheCompressed/tree/1.18" #optional
logoFile="AllTheCompressed.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Pdiddy973" #optional
description='''
adds 1-9x compressed versions of blocks, and recipes.
'''
[[dependencies.allthecompressed]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.allthecompressed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
